### ISSUE TITLE
Flash of black rectangle

### ISSUE THREAD

**Issue by GeoffreyPlitt** [naoufal/react-native-accordion#28]
I'm seeing a flash of black rectangle when running the example, on both Android and iOS.

**Comment by naoufal** [comment]
@GeoffreyPlitt can you provide a code snippet and video example?

**Comment by tnortman** [comment]
@naoufal Hi, I am having the same problem. You will see in the video the black box flashing as @GeoffreyPlitt says. There is also a bug where the ListView does not render all the way down the screen until the user drags down/up (seen towards end of video) .[Accordion Video](https://vimeo.com/172021881)

**Comment by tnortman** [comment]
After some playing around, the black flash (for me) came into effect when I had a 'marginTop' on the header. This is fixed by simply moving the 'marginTop' to the Accordion component itself.

That being said I am still having the issue where half of the Accordion's do not show up upon initial render until the user scrolls.

**Comment by ddresch** [comment]
@tnortman not sure if you mean the same issue.

But there is a prop of Accordion, called `underlayColor` you can use that to set the color of the TouchableHighlight which is used for the header. So like that you can adjust it to your desired background color.

**Comment by sergiocloud** [comment]
I have solved that problem with underlayColor prop setting to white.

**Comment by naoufal** [comment]
Thanks for reporting back @sergiocloud.
